version: '3.1'
services:
  mysql:
    image: 'mysql:8.0'
    working_dir: /application
    volumes:
      - '.:/application'
    environment:
      - MYSQL_ROOT_PASSWORD=eulabs
      - MYSQL_DATABASE=eulabs
      - MYSQL_USER=eulabs
      - MYSQL_PASSWORD=eulabs
    ports:
      - '3304:3306'
  api:
    build:
      dockerfile: Dockerfile
    environment: 
      - PORT=1323
      - MYSQL_HOST=localhost
      - MYSQL_USER=eulabs
      - MYSQL_PORT=3304
      - MYSQL_DB_NAME=eulabs
      - MYSQL_PASSWORD=eulabs
    ports: 
      - '1323:1323'

networks:
  api-network:
    name: api-localhost
    driver: bridge